common: common-1.0

spring:
  jpa:
    database: mysql #设置方言
    show_sql: true #显示sql
    hibernate:
#      ddl-auto: update
      format_sql: true #格式化sql
#      naming:
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #设置数据库sql、不加下划线
  redis:
    host: 39.107.226.36
  port: 6379
  pool:
    max-idle: 100
    min-idle: 1
    max-active: 1000
    max-wait: -1
#eureka配置
eureka:
  instance:
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
    serviceUrl:
      defaultZone: http://39.107.226.36:8762/eureka/