#端口设置
server:
  port: 8763
spring:
  profile: dev-1.0
redis:
  host: 39.107.226.36
  password:
eureka:
  client:
    serviceUrl:
      defaultZone: http://39.107.226.36:8762/eureka/
#      defaultZone: http://127.0.0.1:8761/eureka/