#端口设置
server:
  port: 9093
spring:
  profile: pro-1.0
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl #设置数据库sql、不加下划线
  application:
    name: member-server
  datasource:
    ##数据库连接信息
    name: member
    url: jdbc:mysql://39.107.226.36:3306/rbac?useUnicode=true&characterEncoding=utf8
logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder : trace
