#端口设置
server:
  port: 9005

spring:
  profile: dev-1.0
  datasource:
    ##数据库连接信息
    name: member
    url: jdbc:mysql://39.107.226.36:3306/oauth2?useUnicode=true&characterEncoding=utf8
  freemarker:
    request-context-attribute: request

#开启feign的hystrix
feign:
  hystrix:
    enabled: false
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false #关闭熔断器超时检测时间功能，也就是不超时
#        isolation:
#          thread:
#            timeoutInMilliseconds: 5000  #设置熔断器检测时间（默认1秒）

eureka:
  instance:
    ##续约更新时间间隔设置5秒，m默认30s
    lease-renewal-interval-in-seconds: 5
    ##续约到期时间10秒，默认是90秒
    lease-expiration-duration-in-seconds: 10
  client:
    service-url:
#      defaultZone: http://127.0.0.1:8761/eureka/
      defaultZone: http://39.107.226.36:8762/eureka/