#端口设置
server:
  port: 9003
#spring配置
spring:
  profile: pro-1.0
  cloud:
    gateway:
      filter:
        remove-non-proxy-headers:
          headers:
          - dummy
      routes:
      - id:  oauths
        # 重点！/info必须使用http进行转发，lb代表从注册中心获取服务
        uri: lb://OAUTH-SERVER
        predicates:
        # 重点！转发该路径！,/userapi/**,
        - Path=/oauths/**
        # http://localhost:6601/userapi/user/users/2, 必须加上StripPrefix=1，否则访问服务时会带上userapi
        #而不是我们期望的去掉userapi，只保留**部分
        filters:
        - StripPrefix=1
      - id:  oauthr
        uri: lb://OAUTH-RESOURCE
        predicates:
        - Path=/oauthr/**
        filters:
        - StripPrefix=1
      - id:  customer
        uri: lb://CUSTOMER-SERVER
        predicates:
        - Path=/customer/**
        filters:
        - StripPrefix=1